services:
  postgres:
    container_name: pg_vocagame_test
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=dwiw
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=technical_test
    restart: no
