// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type TransactionStatus string

const (
	TransactionStatusCompleted TransactionStatus = "completed"
	TransactionStatusPending   TransactionStatus = "pending"
	TransactionStatusFailed    TransactionStatus = "failed"
)

func (e *TransactionStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TransactionStatus(s)
	case string:
		*e = TransactionStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TransactionStatus: %T", src)
	}
	return nil
}

type NullTransactionStatus struct {
	TransactionStatus TransactionStatus
	Valid             bool // Valid is true if TransactionStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTransactionStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TransactionStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TransactionStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTransactionStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TransactionStatus), nil
}

type TransactionTypes string

const (
	TransactionTypesPurchase   TransactionTypes = "purchase"
	TransactionTypesDeposit    TransactionTypes = "deposit"
	TransactionTypesWithdrawal TransactionTypes = "withdrawal"
	TransactionTypesTransfer   TransactionTypes = "transfer"
)

func (e *TransactionTypes) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TransactionTypes(s)
	case string:
		*e = TransactionTypes(s)
	default:
		return fmt.Errorf("unsupported scan type for TransactionTypes: %T", src)
	}
	return nil
}

type NullTransactionTypes struct {
	TransactionTypes TransactionTypes
	Valid            bool // Valid is true if TransactionTypes is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTransactionTypes) Scan(value interface{}) error {
	if value == nil {
		ns.TransactionTypes, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TransactionTypes.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTransactionTypes) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TransactionTypes), nil
}

type Product struct {
	ID           int32
	Name         string
	Description  pgtype.Text
	Price        int32
	Availability int32
}

type RefreshTokenWhitelist struct {
	ID           int32
	UserID       int32
	RefreshToken pgtype.UUID
	ExpiresAt    pgtype.Timestamp
	CreatedAt    pgtype.Timestamp
}

type SecM struct {
	PrivateKey []byte
}

type TransactionHistory struct {
	ID           int32
	FromWalletID pgtype.Int4
	ToWalletID   pgtype.Int4
	ProductID    pgtype.Int4
	Amount       int32
	Quantity     pgtype.Int4
	TType        TransactionTypes
	TStatus      TransactionStatus
	CreatedAt    pgtype.Timestamp
}

type User struct {
	ID             int32
	Username       string
	Email          string
	HashedPassword string
	IsVerified     bool
	CreatedAt      pgtype.Timestamp
}

type Wallet struct {
	ID        int32
	UserID    int32
	Balance   int32
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}
